// Generated by CoffeeScript 1.3.1
(function() {
  var BasicSkin;

  BasicSkin = (function() {

    function BasicSkin() {}

    BasicSkin.prototype.container = null;

    BasicSkin.prototype.txtProject = null;

    BasicSkin.prototype.tracking = null;

    BasicSkin.init = function(_container) {
      var container, id, tracking, txtProject;
      id = "#" + _container.element.context.id;
      console.log("skin::init", _container, _container.element.context.id, id);
      container = $(id);
      txtProject = $("<label></label>");
      return tracking = $("<div></div>");
    };

    true;


    BasicSkin.execute = function(handler, data) {
      var i;
      console.log("skin::execute", data, container);
      for (i in data) {
        console.log("->:", data[i]);
      }
      txtProject.text(data[0].completition + " " + data[0].major + "." + data[0].min);
      tracking.html(data[0].completition);
      container.append(txtProject);
      return container.append(tracking);
    };

    true;


    return BasicSkin;

  }).call(this);

}).call(this);
