// Generated by CoffeeScript 1.3.1
(function() {

  (function() {
    var skin;
    return skin = function() {
      var tracking, txtProject;
      txtProject = null;
      tracking = null;
      this.init = function() {
        txtProject = $("#project");
        return tracking = $("#percent");
      };
      this.execute = function(data) {
        txtProject.html(data.project);
        return tracking.html(data.percent);
      };
      return this.skinSelected = function(skinName) {
        if (skinName === undefined) {
          return _skin;
        }
      };
    };
  });

}).call(this);
